### ISSUE TITLE
Create string variables in the bar-chart.component.ts to replace the "hard coded strings" found in the bar-chart.component.html files.

### ISSUE THREAD

**Issue by jayhamilton** [jayhamilton/ngx-dynamic-dashboard-framework#22]
Within the bar-chart.component.html page change lines 17, 18 and 19 with variables. You will define the variables within the bar-chart.component.ts file starting on line 13. These will be string variables and will reflect the type of information displayed in the bar chart. 

See: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/declare-string-variables

**Comment by Jhamilton2025** [comment]
CHanged legend and side titles
